name: uber_driver_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  lottie: ^1.2.1
  cupertino_icons: ^1.0.4
  image_picker: ^0.8.4+4
  font_awesome_flutter: ^9.2.0
  flutter_launcher_icons: ^0.9.2

  #state management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get: ^4.6.1

  #firebase
  firebase_auth: 
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0

  #map
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.3
  flutter_polyline_points: ^1.0.0

  # dependency injection
  get_it: ^7.2.0
  intl: ^0.17.0

  #rxdart
  rxdart: ^0.27.3
  modal_bottom_sheet: ^2.0.0

  #network connectivity
  connectivity_plus: ^2.2.0

  # for calling
  flutter_phone_direct_caller: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logo.png"

flutter:

  uses-material-design: true


  assets:
     - assets/
